FROM docker.io/library/busybox:musl AS extract

ARG LTEX_LS_PLUS_RELEASE=18.6.1
RUN (set -xo pipefail; wget -qO- "https://github.com/ltex-plus/ltex-ls-plus/releases/download/${LTEX_LS_PLUS_RELEASE}/ltex-ls-plus-${LTEX_LS_PLUS_RELEASE}.tar.gz" | tar -xzC /) && mv /ltex-ls-plus-${LTEX_LS_PLUS_RELEASE} /ltex-ls-plus

FROM scratch

COPY --from=extract /ltex-ls-plus /opt/ltex-ls-plus
