position=bottom-right
#font_scale=0.5
hud_compact
hud_no_margin
gpu_core_clock
cpu_mhz
#gpu_temp
#gpu_power
#cpu_power
vram
gpu_mem_clock
battery=0
#frame_timing
#fps=0
table_columns=3
#core_load
#core_bars
font_size=12
throttling_status_graph
fps_metrics=avg,0.01
fps_limit=75
