[preset 1]
time
gpu_stats
gpu_temp
gpu_core_clock
gpu_power
cpu_stats
cpu_temp
cpu_power
cpu_mhz
core_load
core_bars
vram
fps
fps_metrics=avg,0.01
frametime
engine_short_names
exec_name
present_mode
display_server
hud_compact
wine
winesync
throttling_status