[main]
# The default PPD profile
default=balanced
battery_detection=false
sysfs_acpi_monitor=true

[profiles]
# PPD = TuneD
power-saver=powersave
balanced=balanced-battery
performance=throughput-performance

[battery]
# PPD = TuneD
balanced=balanced-battery
