context.modules = [
    {   
        name = libpipewire-module-loopback
        args = {
            audio.position = [ FL FR ]
            capture.props = {
                media.class = Audio/Sink
                node.name = my_sink
                node.description = "Micspam In"
            }
            playback.props = {
                media.class = Audio/Source
                node.name = "my_sink.output"
                node.passive = true
                node.description = "Micspam Out"
            }
        }
    }
]

