profile=fast
af=lavfi=dynaudnorm
alang=jp,jpn,en,eng
hwdec=auto-safe
keepaspect-window=no
osc=no
osd-font=Liberation Sans
quiet
save-position-on-quit
slang=eng,en
sub-ass-override=strip
sub-auto=all
sub-font=Liberation Sans
sub-pos=97
vd-lavc-fast=yes
vo=gpu-next
window-maximized=yes
ytdl-format=best[height=720][fps=60]/bestvideo[height=720][fps=60]+bestaudio/bestvideo[height<=480][vcodec!*=av01]+bestaudio
ytdl-raw-options=format-sort="hasvid,res:720,hasaud,+size",verbose=,cookies-from-browser=firefox


