profile=fast
af=lavfi=dynaudnorm
alang=jp,jpn,en,eng
hwdec=auto-safe
keepaspect-window=no
osc=no
osd-font=Liberation Sans
save-position-on-quit
slang=eng,en
sub-ass-override=strip
sub-auto=all
sub-font=Liberation Sans
sub-pos=97
#vd-lavc-fast=yes
vo=gpu-next
window-maximized=yes
ytdl-format=bestvideo[height<=720]+bestaudio
ytdl-raw-options=verbose=,cookies-from-browser=firefox
keep-open

# scale=ewa_lanczos
# cscale=ewa_lanczos
target-colorspace-hint=yes
#hdr-compute-peak=yes
#video-sync=display-vdrop
