set -g default-terminal "tmux-256color"
set -g base-index 1
setw -g pane-base-index 1
set -g default-shell "/bin/fish"
set -g status-keys emacs
set -g mouse on
set -g focus-events off
setw -g aggressive-resize off
set -s escape-time 0
set -g repeat-time 0
set -g set-titles on
set -g status-style bg=default,fg=default
set -g status-right "#{?window_bigger,[#{window_offset_x}#,#{window_offset_y}] ,}#{=21:pane_title}"
setw -g mode-keys vi
