ARG FEDORA_RELEASE=43

FROM quay.io/fedora/fedora:${FEDORA_RELEASE} AS install

RUN useradd -mU -d /home/user -u 1000 user

USER 1000

RUN (curl -fsSL https://sh.rustup.rs | sh -s -- -y --profile minimal -c rustfmt,rust-analyzer --no-modify-path)

FROM scratch

COPY --from=install /home/user/.cargo /.cargo
COPY --from=install /home/user/.rustup /.rustup
