on:
  push:
    branches:
    - default
    paths:
    - images/Containerfile.base
  schedule:
    - cron: "0 0 1,15 * *" # midnight on the 1st and 15th of each month
  workflow_dispatch:
jobs:
  build_push:
    uses: ./.github/workflows/build+push.yml
    with:
      image: base
      containerfile: ./images/Containerfile.base
