on:
  workflow_call:
    inputs: &inputs
      image:
        required: true
        type: string
      containerfile:
        required: true
        type: string
  workflow_dispatch:
    inputs: *inputs
jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
      TAG: ghcr.io/${{ github.repository_owner }}/${{ inputs.image }}
    steps:
    - name: Log in to ghcr.io
      uses: redhat-actions/podman-login@v1
      with:
        username: ${{ github.actor }}
        password: ${{ github.token }}
        registry: ${{ env.IMAGE_REGISTRY }}
    - uses: actions/checkout@v4
    - name: dirname ${{ inputs.containerfile }}
      id: dirname
      run: |
        echo "context=$(dirname ${{ inputs.containerfile }})" >> "$GITHUB_OUTPUT"
    - name: Build ${{ inputs.image }}
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ env.TAG }}
        context: ${{ steps.dirname.outputs.context }}
        tags: latest ${{ env.GITHUB_SHA }}
        build-args: |
          FEDORA_RELEASE=43
        layers: true
        oci: true
        extra-args: |
          --cache-from=${{ env.TAG }}
          --cache-to=${{ env.TAG }}
        containerfiles: |
          ${{ inputs.containerfile }}
    - name: Push To GHCR
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ inputs.image }}
        tags: latest
        registry: ${{ env.IMAGE_REGISTRY }}
