on:
  push:
    branches:
    - default
    paths:
    - images/Containerfile.devcontainer
  image_version:
    names:
    - ghcr.io/lina-bh/base
    - ghcr.io/lina-bh/ltex-ls-plus
    - ghcr.io/lina-bh/texlive
    - ghcr.io/lina-bh/rust
  workflow_dispatch:
jobs:
  build_push:
    uses: ./.github/workflows/build+push.yml
    with:
      image: devcontainer
      containerfile: ./images/Containerfile.devcontainer
    permissions:
      contents: read
      packages: write
