on:
  push:
    branches:
    - default
    paths:
    - images/Containerfile.devcontainer
  image_version:
    names:
    - ghcr.io/${{ env.GITHUB_REPOSITORY_OWNER }}/base
    - ghcr.io/${{ env.GITHUB_REPOSITORY_OWNER }}/ltex-ls-plus
    - ghcr.io/${{ env.GITHUB_REPOSITORY_OWNER }}/texlive
    - ghcr.io/${{ env.GITHUB_REPOSITORY_OWNER }}/rust
  workflow_dispatch:
jobs:
  build_push:
    uses: ./.github/workflows/build+push.yml
    with:
      image: devcontainer
      containerfile: ./images/Containerfile.devcontainer
permissions:
  contents: read
  packages: write
