on:
  push:
    branches:
    - default
    paths:
    - images/Containerfile.devcontainer
    - .github/workflows/devcontainer.yml
  image_version:
    names:
    - ghcr.io/lina-bh/base
    - ghcr.io/lina-bh/ltex-ls-plus
    - ghcr.io/lina-bh/texlive
    versions:
    - latest
  workflow_dispatch:
jobs:
  build_push:
    uses: ./.github/workflows/build_push.yml
    with:
      image: devcontainer
      containerfile: ./images/Containerfile.devcontainer
    permissions:
      contents: read
      packages: write
