on:
  push:
    branches:
    - default
    paths:
    - images/Containerfile.base
  workflow_dispatch:
jobs:
  build+push:
    uses: ./.github/workflows/build+push.yml
    with:
      image: base
      containerfile: ./images/Containerfile.base
