on:
  push:
    branches:
    - default
    paths:
    - images/Containerfile.ltex-ls-plus
  workflow_dispatch:
jobs:
  build_push:
    uses: ./.github/workflows/build+push.yml
    with:
      image: ltex-ls-plus
      containerfile: ./images/Containerfile.ltex-ls-plus
permissions:
  contents: read
  packages: write
