on:
  push:
  workflow_dispatch:
  # schedule:
  # - cron: '0 0 * * *'
jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
    strategy:
      matrix:
        image: [devcontainer]
    steps:
    - name: Log in to ghcr.io
      uses: redhat-actions/podman-login@v1
      with:
        username: ${{ github.actor }}
        password: ${{ github.token }}
        registry: ${{ env.IMAGE_REGISTRY }}
    - uses: actions/checkout@v4
    - id: build
      run: |
        image_id="$(just ${{ matrix.image }})"
        echo "IMAGE_ID=$image_id" | tee -a "$GITHUB_OUTPUT"
    - name: Push To GHCR
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ matrix.image }}
        tags: latest ${{ steps.build.outputs.IMAGE_ID }}
        registry: ${{ env.IMAGE_REGISTRY }}
